config/routes.rb
Rails.application.routes.draw do
  get 'likes/create'
  get 'likes/destroy'
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  root 'products#index'

  resources :profiles, only: [:edit, :update]
  resources :addresses, only: [:edit, :update, :new, :create]

  resources :users, only: [:edit, :update] do
    collection do
      get 'likes'
    end

    member do
      get 'history'
    end
  end
  
  devise_scope :user do
    get "log_in", to: "users/sessions#new"
    get 'log_out', to: "users#log_out"
    delete 'log_out', to: 'users/sessions#destroy'

  end

  resources :products do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'search'
    end
    resources :evaluations, only: [:new, :create]
    resources :likes, only: [:create, :destroy]
    resources :comments, only: :create
    post "", to: "evaluations#create"
    
    member do
      get 'purchase'
      get 'pay'
    end

  end

  resources :likes, only: [:index, :show, :create, :destroy]

  resources :categories, only: [:index, :show]

  resources :cards, only: [:new, :create, :show, :destroy]

  resources :users, only: [:index, :show] do
    collection do
      get :likes
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true

  has_one :profile
  accepts_nested_attributes_for :profile
  has_one :address
  has_one :card
  has_many :products
  has_many :comments
  has_many :evaluations

  has_many :likes, dependent: :destroy
  has_many :like_products, through: :likes, source: :product
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController

  def new
    @parents = Category.all.order("id ASC").limit(1)
    @user = User.new
    @profile = @user.build_profile
  end
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    @parents = Category.all.order("id ASC").limit(1)
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  def new
    @parents = Category.all.order("id ASC").limit(1)
    @user = User.new
    @profile = @user.build_profile
  end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  def destroy
    # session[:user_id] = nil
    # flash[:notice] = "ログアウトしました"
    # redirect_to root_path
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_parent

  def index
    if user_signed_in?
      @user = User.find(current_user.id)
      @product = Product.find_by(user_id: params[:id])
      @products = @user.products
      @product_sell = Product.where(user_id: current_user.id, purchaser_id: nil)
      @product_selled = Product.where(user_id: current_user.id).where.not(purchaser_id: nil)
      @profile = Profile.find(@user.id)
      @address = Address.where(user_id: current_user.id).first
      @evaluation_good_sum = Evaluation.where(user_id: current_user.id, evaluation: 1)
      @evaluation_normal_sum = Evaluation.where(user_id: current_user.id, evaluation: 2)
      @evaluation_bad_sum = Evaluation.where(user_id: current_user.id, evaluation: 3)
    else
      redirect_to root_path
    end
  end

  def show
    if user_signed_in?
      @user = User.find(current_user.id)
      @product = Product.find_by(user_id: params[:id])
      @products = Product.where(user_id: params[:id])
      @product_sell = Product.where(user_id: params[:id], purchaser_id: nil)
      @product_selled = Product.where(user_id: params[:id]).where.not(purchaser_id: nil)
      @profile = Profile.find(params[:id])
      @evaluation_good_sum = Evaluation.where(user_id: current_user.id, evaluation: 1)
      @evaluation_normal_sum = Evaluation.where(user_id: current_user.id, evaluation: 2)
      @evaluation_bad_sum = Evaluation.where(user_id: current_user.id, evaluation: 3)
    else
      redirect_to root_path
    end

  end

  def destroy
    # session[:user_id] = nil
    # flash[:notice] = "ログアウトしました"
    # redirect_to root_path
  end

  def log_out
    @user = User.find(current_user.id)
  end

  def likes
    @user = User.find_by(id: params[:id])
    @likes = Like.where(user_id: current_user.id)
  end

  def history
    @products = Product.where(purchaser_id: params[:id])
  end


  def set_parent
    @parents = Category.all.order("id ASC").limit(10)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_side-bar.html.haml
.mypage-side
  .maypage-sidebar
    %ul.mypage-sidebar-lists
      %li.mypage-sider-list
        = link_to users_path, class: "mypage-sideber-list__text" do
          %h2.bold
            マイページ
      %li.mypage-sider-list
        = link_to likes_users_path, class: "mypage-sideber-list__text" do
          %h2.bold
            いいね
      %li.mypage-sider-list
        = link_to new_product_path, class: "mypage-sideber-list__text" do
          %h2.bold
            出品する
      %li.mypage-sider-list
        = link_to history_user_path(current_user.id), class: "mypage-sideber-list__text" do
          %h2.bold
            購入した商品
    .mypage-nav-head
      設定
    %ul.mypage-nav-list
      %li
        = link_to edit_profile_path(@user), class: "mypage-sideber-list__text" do
          %h2.bold
            プロフィール
      %li
        -if @address == nil 
          = link_to new_address_path, class: "mypage-sideber-list__text" do
            %h2.bold
              発送元・お届け先住所
        -else
          = link_to edit_address_path(@user), class: "mypage-sideber-list__text" do
            %h2.bold
              発送元・お届け先住所
      %li
        = link_to card_path(@user), class: "mypage-sideber-list__text" do
          %h2.bold
            お支払い方法
      %li
        = link_to  destroy_user_session_path, class: "mypage-sideber-list__text" do
          %h2.bold
            ログアウト

app/views/users/_user-info-regular.html.haml
.mypage-userinfo-regular
  %ul.mypage-userinfo-regular__lists
    %li.mypage-userinfo-regular__lists__name
      = link_to user_path(@user), class: "mypage-userinfo-regular__lists__link" do
        = @user.nickname + "さん"
    %li.mypage-userinfo-regular__lists__img
      = link_to user_path(@user), class: "mypage-userinfo-regular__lists__link" do
        = image_tag 'member_photo_noimage_thumb.png', height: '70px', width: '70px', class: 'mypage-userinfo-regular__lists__img__data'

app/views/users/history.html.haml
- unless user_signed_in?
  = render new_user_session_path
.wrapper-category
  .categoies__contents__top
    .categories____contents__top__name
      購入した商品一覧
  .categories__item-box
    - @products.each do |product|
      .categories__item-box__product
        = link_to product_path(product), class: "category_btn" do
          .categories__item-box__image
            - product.images.limit(1).each do |images|
              = image_tag images.image.to_s, size: "200x200", class: "categories__item-box__image__price"
          .categories__item-box__price
            .categories__item-box__price__box
              ¥ #{product.price.to_s(:delimited, delimiter: ',')}
          -if product.purchaser_id.present?
            .items-box_photo__sold-index
              .items-box_photo__sold-index__inner
                SOLD
      

app/views/users/index.html.haml
.mypage-main
  .main-content-wrapper
    =render partial: 'users/side-bar'
    .mypage-content
      .user-details
        %section.user-profile
          .mypage-userinfo-regular-user-index
            %ul.mypage-userinfo-regular__lists
              %li.mypage-userinfo-regular__lists__name-index-show
                = link_to user_path(@user), class: "mypage-userinfo-regular__lists__link" do
                  = @user.nickname + "さん"
              %li.mypage-userinfo-regular__lists__img-show-index
                = link_to user_path(@user), class: "mypage-userinfo-regular__lists__link" do
                  - if @profile.image.present?
                    = image_tag @profile.image.to_s, height: '70px', width: '70px', class: 'mypage-userinfo-regular__lists__img__data'
                  -else
                    = image_tag 'member_photo_noimage_thumb.png', height: '70px', width: '70px', class: 'mypage-userinfo-regular__lists__img__data'
          .user-evaluation
            .user-evaluation__box
              %ul.evaluation
                %li.evaluation
                  = icon('fas', 'grin',  class: "good")
                  %i
                    = @evaluation_good_sum.count
                  
                %li.evaluation
                  = icon('fas', 'meh',  class: "normal")
                  %i
                    = @evaluation_normal_sum.count
                  
                %li.evaluation
                  = icon('fas', 'frown',  class: "bad")
                  %i
                    = @evaluation_bad_sum.count        

          .text-box
            = @profile.introduction
          .tabs
            .tabs-box
              %input#tab-1{:checked => "checked", :name => "tab-radio", :type => "radio"}/
              %label.tab-label{:for => "tab-1"}出品中
              %input#tab-2{:name => "tab-radio", :type => "radio"}/
              %label.tab-label{:for => "tab-2"}売却済み
              .tab-content.tab-1-content
                - @product_sell.each do |sell|
                  .image_box
                    = link_to product_path(sell), class: "sell-box" do
                      - sell.images.limit(1).each do |images|
                        =image_tag images.image.to_s, size:"110x110", class: "sell-box_img"
              .tab-content.tab-2-content
                - @product_selled.each do |selled|
                  .image_box
                    = link_to product_path(selled), class: "sell-box" do
                      .image
                        - selled.images.limit(1).each do |images|
                          =image_tag images.image.to_s, size:"110x110", class: "sell-box_img"
                        -if selled.purchaser_id.present?
                          .items-box_photo__sold
                            .items-box_photo__sold__inner
                              SOLD
= render partial: 'layouts/footer'
= render partial: 'layouts/post-btn'

app/views/users/likes.html.haml
- unless user_signed_in?
  = render new_user_session_path
.wrapper-category
  .categoies__contents__top
    .categories____contents__top__name
      お気に入り商品の一覧
  .categories__item-box
    - current_user.like_products.each do |product|
      .categories__item-box__product
        = link_to product_path(product), class: "category_btn" do
          .categories__item-box__image
            - product.images.limit(1).each do |images|
              = image_tag images.image.to_s, size: "200x200", class: "categories__item-box__image__price"  
          .categories__item-box__price
            .categories__item-box__price__box
              ¥ #{product.price.to_s(:delimited, delimiter: ',')}
          -if product.purchaser_id.present?
            .items-box_photo__sold-index
              .items-box_photo__sold-index__inner
                SOLD
      

app/views/users/log_out.html.haml
.mypage-main
  .mypage-side
    %nav.mypage-nav
      %ul.mypage-nav-list
        %li
          = link_to "マイページ", users_path
        %li
          = link_to "いいね", "#"
        %li
          = link_to "出品する", new_product_path
        %li
          = link_to "出品した商品-取引中", "#"
        %li
          = link_to "出品した商品-売却済み", "#"
        %li
          = link_to "購入した商品", "#"
      .mypage-nav-head
        メルペイ
      %ul.mypage-nav-list
        %li
          = link_to "ポイント", "#"
        %li
      .mypage-nav-head
        設定
      %ul.mypage-nav-list
        %li
          = link_to "プロフィール", edit_user_profile_path(@user)
        %li
          = link_to "発送元・お届け先住所", edit_user_address_path(@user)
        %li
          = link_to "支払い方法", new_card_path
        %li
          = link_to "ログアウト", log_out_path, method: :get
  .logout-content
    -# = form_with url: log_out_path, class: "form" do |form|
    .form
      = link_to "ログアウト", log_out_path, method: :delete, class: "logout-button"
      -# = form.submit "ログアウト", class: "logout-button"

app/views/users/show.html.haml
.contents-wrapper
  .user-details
    %section.user-profile
      .user-icon
        = link_to user_path(params[:id]) do
          - if @profile.image.present?
            = image_tag @profile.image.to_s, size: "500×500", class: "user_img"
          -else
            = image_tag "member_photo_noimage_thumb.png",size: "180x180", class: "user_img"
          .product-user-name
          = @user.nickname
      .user-evaluation
        .user-evaluation__box
          %ul.evaluation
            %li.evaluation
              = icon('fas', 'grin',  class: "good")
              %i
                = @evaluation_good_sum.count
              
            %li.evaluation
              = icon('fas', 'meh',  class: "normal")
              %i
                = @evaluation_normal_sum.count
              
            %li.evaluation
              = icon('fas', 'frown',  class: "bad")
              %i
                = @evaluation_bad_sum.count         

      .text-box
        = @profile.introduction
      .tabs
        .tabs-box
          %input#tab-1{:checked => "checked", :name => "tab-radio", :type => "radio"}/
          %label.tab-label{:for => "tab-1"}出品中
          %input#tab-2{:name => "tab-radio", :type => "radio"}/
          %label.tab-label{:for => "tab-2"}売却済
          .tab-content.tab-1-content
            - @product_sell.each do |sell|
              .image_box
                = link_to product_path(sell), class: "sell-box" do
                  - sell.images.limit(1).each do |images|
                    =image_tag images.image.to_s, size:"110x110", class: "sell-box_img"
          .tab-content.tab-2-content
            - @product_selled.each do |selled|
              .image
                = link_to product_path(selled), class: "sell-box" do
                  .image
                    - selled.images.limit(1).each do |images|
                      =image_tag images.image.to_s, size:"110x110", class: "sell-box_img"
                  -if selled.purchaser_id.present?
                    .items-box_photo__sold
                      .items-box_photo__sold__inner
                        SOLD
=render partial: 'layouts/footer'
=render partial: 'layouts/post-btn'