config/routes.rb
Rails.application.routes.draw do
  get 'likes/create'
  get 'likes/destroy'
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  root 'products#index'

  resources :profiles, only: [:edit, :update]
  resources :addresses, only: [:edit, :update, :new, :create]

  resources :users, only: [:edit, :update] do
    collection do
      get 'likes'
    end

    member do
      get 'history'
    end
  end
  
  devise_scope :user do
    get "log_in", to: "users/sessions#new"
    get 'log_out', to: "users#log_out"
    delete 'log_out', to: 'users/sessions#destroy'

  end

  resources :products do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'search'
    end
    resources :evaluations, only: [:new, :create]
    resources :likes, only: [:create, :destroy]
    resources :comments, only: :create
    post "", to: "evaluations#create"
    
    member do
      get 'purchase'
      get 'pay'
    end

  end

  resources :likes, only: [:index, :show, :create, :destroy]

  resources :categories, only: [:index, :show]

  resources :cards, only: [:new, :create, :show, :destroy]

  resources :users, only: [:index, :show] do
    collection do
      get :likes
    end
  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user

  validates :first_name,
            :last_name,
            :first_name_kana,
            :last_name_kana,
            :zip_code,
            :prefecture,
            :city,
            :street_number,
            presence: { message: "を入力してください"}

  validates :zip_code, format: {with: /\A[0-9]{7}\z/}

  enum prefecture: {
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47
  }
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  has_ancestry
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/evaluation.rb
class Evaluation < ApplicationRecord
  belongs_to :user
  belongs_to :product

  # 同じ商品に対して一意性
  validates :product_id, uniqueness: true
end

app/models/image.rb
class Image < ApplicationRecord
  # config.autoload_paths += Dir[Rails.root.join('app', 'uploaders')]
  mount_uploader :image, ImageUploader
  belongs_to :product
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :product, counter_cache: :likes_count
end

app/models/preparation_term.rb
class PreparationTerm < ApplicationRecord
  has_many :products

  enum term: {
    １〜２日で発送:1,
    ２〜３日で発送:2,
    ３〜７日で発送:3
  }
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  belongs_to :category
  belongs_to :brand, optional: true
  belongs_to :product_condition
  belongs_to :preparation_term
  belongs_to :shipping_region
  belongs_to :shipping_payer, optional: true
  has_many :comments, dependent: :destroy
  has_many :evaluations, dependent: :destroy

  validates :images, presence: { message: "を入力してください"}
  validates :name,  presence: { message: "を入力してください"}, length: { maximum: 40 }
  validates :introduction,  presence: { message: "を入力してください"}
  validates :price, presence: { message: "を入力してください"}
  validates :price, :numericality => { greater_than: 300, less_than: 9999999 } 
  
  has_many :likes, dependent: :destroy
  

  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end

  def self.search(keyword)
    return Product.all unless keyword
    Product.where('name LIKE?', "%#{keyword}%")
  end

end

app/models/profile.rb
class Profile < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user

  #validates_associated :user
  validates :first_name, :last_name, format: { with: /\A[ぁ-んァ-ン一-龥]/,
    message: "全角で入力してください" }
  validates :first_name_kana, :last_name_kana, format: { with: /\A[ァ-ヶー－]+\z/,
    message: "全角カナで入力してください" }
  validates :birth_date, presence: true
end

app/models/shipping_payer.rb
class ShippingPayer < ApplicationRecord
  has_many :products
end

app/models/shipping_region.rb
class ShippingRegion < ApplicationRecord
  has_many :products

  enum region: {
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true

  has_one :profile
  accepts_nested_attributes_for :profile
  has_one :address
  has_one :card
  has_many :products
  has_many :comments
  has_many :evaluations

  has_many :likes, dependent: :destroy
  has_many :like_products, through: :likes, source: :product
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  require "payjp"
  before_action :set_parent, except: [:delete]
  before_action :set_card

  def new
    @user = User.find(current_user.id)
    card = Card.where(user_id: current_user.id)
    redirect_to card_path(current_user.id) if card.exists?
    @profile = Profile.find(current_user.id)
  end
  
  def create
    #payjpとCardのデータベース作成
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    #保管した顧客IDでpayjpから情報取得
    if params['payjp-token'].blank?
      redirect_to new_card_path
    else
      customer = Payjp::Customer.create(
        description: 'test',
        card: params['payjp-token'],
        metadata: {user_id: current_user.id}
        )
        @card = Card.new(user_id: current_user.id, payjp_id: customer.id)
        if @card.save
          redirect_to card_path(current_user.id)
        else
          redirect_to new_card_path
        end
      end
    end
    
    def destroy
      #PayjpとCardデータベースを削除
      card = Card.find_by(user_id: current_user.id)
      if card.blank?
      else
        Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
        customer = Payjp::Customer.retrieve(@card.payjp_id)
        customer.delete
        card.delete
      end
      redirect_to new_card_path
    end
    
    def show
      #Cardのデータpayjpに送り情報を取り出す
    @user = User.find(current_user.id)
    @profile = Profile.find(current_user.id)
    card = Card.find_by(user_id: current_user.id)
    if card.blank?
      redirect_to new_card_path 
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(@card.payjp_id)
      @default_card_information = customer.cards.retrieve(customer.default_card)
    end
  end

  private
  def set_parent
    @parents = Category.all.order("id ASC").limit(10)
  end
  
  def set_card
    @card = Card.where(user_id: current_user.id).first if Card.where(user_id: current_user.id).present?
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/new.html.haml
.content
  .content__main
    =render partial: 'users/side-bar'
    .mypage-rightcontent
      =render partial: 'users/user-info-regular'
      .mypage-mainbox
        .mypage-mainbox__credit-card
          .card-title
            カード情報登録
          = form_tag(cards_path, method: :post, id: 'charge-form', class: 'card-form',  name: "inputForm") do
            .card-form__number
              %label カード番号
              .require 必須
              .card-form__number--form
                = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number", class: "card-form__number--form number-field"
                %ul.signup-card-list
                  %li
                    = image_tag "https://www-mercari-jp.akamaized.net/assets/img/card/visa.svg?238737266",width:"49px",height:"20px"
                  %li
                    = image_tag "https://www-mercari-jp.akamaized.net/assets/img/card/master-card.svg?238737266",width:"34px",height:"20px"
                  %li
                    = image_tag "https://www-mercari-jp.akamaized.net/assets/img/card/saison-card.svg?238737266",width:"30px",height:"20px"
                  %li
                    = image_tag "https://www-mercari-jp.akamaized.net/assets/img/card/jcb.svg?238737266",width:"32px",height:"20px"
                  %li
                    = image_tag "https://www-mercari-jp.akamaized.net/assets/img/card/american_express.svg?238737266",width:"21px",height:"20px"
                  %li
                    = image_tag "https://www-mercari-jp.akamaized.net/assets/img/card/dinersclub.svg?238737266",width:"32px",height:"20px"
                  %li
                    = image_tag "https://www-mercari-jp.akamaized.net/assets/img/card/discover.svg?238737266",width:"32px",height:"20px"
                %br
            .card-form__security-date
              %label 有効期限
              .require 必須
              .card-form__security-date--select
                %select#exp_month{name: "exp_month", type: "text"}
                  %option{value: ""} --
                  %option{value: "1"}01
                  %option{value: "2"}02
                  %option{value: "3"}03
                  %option{value: "4"}04
                  %option{value: "5"}05
                  %option{value: "6"}06
                  %option{value: "7"}07
                  %option{value: "8"}08
                  %option{value: "9"}09
                  %option{value: "10"}10
                  %option{value: "11"}11
                  %option{value: "12"}12
                %span 月/
                %select#exp_year{name: "exp_year", type: "text"}
                  %option{value: ""} --
                  %option{value: "2020"}20
                  %option{value: "2021"}21
                  %option{value: "2022"}22
                  %option{value: "2023"}23
                  %option{value: "2024"}24
                  %option{value: "2025"}25
                  %option{value: "2026"}26
                  %option{value: "2027"}27
                  %option{value: "2028"}28
                  %option{value: "2029"}29
                %span 年
                %br
                %br
            .card-form__cvc
              %label セキュリティコード
              .require 必須
              = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc", class: "card-form__cvc--form number-field"
              %br
              #card_token
              %br
            .card-form__submit
              = submit_tag "カードを追加する", id: "token_submit", class: "card-form__submit--btn"
=render partial: 'layouts/footer'
=render partial: 'layouts/post-btn'

app/views/cards/show.html.haml
.content
  .content__main
    =render partial: 'users/side-bar'
    .mypage-rightcontent
      =render partial: 'users/user-info-regular'
      .mypage-mainbox
        .mypage-mainbox__credit-card
          .card-title
            クレジットカード情報
          .card-content
            .card-content__detail
              %br
              = "**** **** **** " + @default_card_information.last4
              %br
              - exp_month = @default_card_information.exp_month.to_s
              - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
              = exp_month + " / " + exp_year
            .card-content__delete
              = form_tag(card_path(current_user.id), method: :delete, id: 'charge-form', class: "card-content__delete--btn", name: "inputForm") do
                %input{ type: "hidden", name: "card_id", value: "" }
                %button.delete-btn 削除する
=render partial: 'layouts/footer'
=render partial: 'layouts/post-btn'