config/routes.rb
Rails.application.routes.draw do
  get 'likes/create'
  get 'likes/destroy'
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  root 'products#index'

  resources :profiles, only: [:edit, :update]
  resources :addresses, only: [:edit, :update, :new, :create]

  resources :users, only: [:edit, :update] do
    collection do
      get 'likes'
    end

    member do
      get 'history'
    end
  end
  
  devise_scope :user do
    get "log_in", to: "users/sessions#new"
    get 'log_out', to: "users#log_out"
    delete 'log_out', to: 'users/sessions#destroy'

  end

  resources :products do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'search'
    end
    resources :evaluations, only: [:new, :create]
    resources :likes, only: [:create, :destroy]
    resources :comments, only: :create
    post "", to: "evaluations#create"
    
    member do
      get 'purchase'
      get 'pay'
    end

  end

  resources :likes, only: [:index, :show, :create, :destroy]

  resources :categories, only: [:index, :show]

  resources :cards, only: [:new, :create, :show, :destroy]

  resources :users, only: [:index, :show] do
    collection do
      get :likes
    end
  end

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  belongs_to :category
  belongs_to :brand, optional: true
  belongs_to :product_condition
  belongs_to :preparation_term
  belongs_to :shipping_region
  belongs_to :shipping_payer, optional: true
  has_many :comments, dependent: :destroy
  has_many :evaluations, dependent: :destroy

  validates :images, presence: { message: "を入力してください"}
  validates :name,  presence: { message: "を入力してください"}, length: { maximum: 40 }
  validates :introduction,  presence: { message: "を入力してください"}
  validates :price, presence: { message: "を入力してください"}
  validates :price, :numericality => { greater_than: 300, less_than: 9999999 } 
  
  has_many :likes, dependent: :destroy
  

  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end

  def self.search(keyword)
    return Product.all unless keyword
    Product.where('name LIKE?', "%#{keyword}%")
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  require "payjp"
  before_action :set_category, only: [:new, :create, :update, :edit]
  before_action :set_parent,   except: [:delete]
  before_action :set_product,  only: [:edit, :show, :update, :purchase, :pay]


  def index
    images = Image.select("id", "image", "product_id")
    @category_parents = Category.where(ancestry: nil).order("id ASC").limit(5)
    @category_products = Product.all
  end

  def new
    @product = Product.new
    @product.images.new
    #@images = @product.build_images
    @category_parent_array = Category.where(ancestry: nil).order(id: "ASC")
    unless user_signed_in?
      redirect_to new_user_session_path
    end
  end

  def create
    @product = Product.create(product_params)

    if @product.save
      redirect_to root_path
    else
      unless @product.images.present?
        @product.images.new
        render 'new'
      else
        render 'new'
      end
    end
  end


  def edit
    grandchild_category = @product.category
    child_category = grandchild_category.parent
    parent_category = grandchild_category.root
    @parent_categories = Category.where(ancestry: nil)

    @category_children_array = []
    Category.where(ancestry: child_category.ancestry).each do |children|
      @category_children_array << children
    end

    @category_grandchildren_array = []
    Category.where(ancestry: grandchild_category.ancestry).each do |grandchildren|
      @category_grandchildren_array << grandchildren
    end
    # ログインかつ、投稿者かつ、商品が売り切れてない場合
    unless user_signed_in? && @product.user_id == current_user.id && @product.purchaser_id.blank?
      redirect_to root_path
    end
  end

  def update

    if params[:product].keys.include?("image") || params[:product].keys.include?("images_attributes")
      if @product.valid?
        if params[:product].keys.include?("image")
        # dbにある画像がedit画面で一部削除してるか確認
          update_images_ids = params[:product][:image].values #投稿済み画像
          before_images_ids = @product.images.ids
          #  商品に紐づく投稿済み画像が、投稿済みにない場合は削除する
          # @product.images.ids.each doで、一つずつimageハッシュにあるか確認。なければdestroy
          before_images_ids.each do |before_img_id|
            Image.find(before_img_id).destroy unless update_images_ids.include?("#{before_img_id}")
          end
        else
          # imageハッシュがない = 投稿済みの画像をすべてedit画面で消しているので、商品に紐づく投稿済み画像を削除する。
          # @product.images.destroy = nil と削除されないので、each do で一つずつ削除する
          before_images_ids = @product.images.ids
          before_images_ids.each do |before_img_id|
            Image.find(before_img_id).destroy
          end

        end
        @product.update(product_params)
        redirect_to action: 'show'
      else
        render 'edit'
      end
    else
      redirect_back(fallback_location: root_path,flash: {success: '画像がありません'})
    end
  end

  def destroy

  end

  def show
    Product.find(params[:id])
    @product = Product.find(params[:id])
    products = Product.where(user_id: @product.user_id)
    @images = @product.images
    @image = @images.first
    @children = @product.category
    @comment = Comment.new
    @comments = @product.comments.includes(:user).order(" created_at DESC ")
    @evaluation = Evaluation.where(product_id: @product.id)

    @evaluation_good_sum = Evaluation.where(user_id: @product.user_id, evaluation: 1)
    @evaluation_normal_sum = Evaluation.where(user_id: @product.user_id, evaluation: 2)
    @evaluation_bad_sum = Evaluation.where(user_id: @product.user_id, evaluation: 3)
  end

  def destroy
    @product = Product.find(params[:id])
    if user_signed_in? && @product.user_id == current_user.id && @product.purchaser_id.blank?
      @product.destroy
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  def purchase
    # showからのページ遷移アクション
    if user_signed_in?
      @user = User.find(current_user.id)
      @images = @product.images
      @image = @images.first
      @address = Address.where(user_id: current_user.id).first
      @card = Card.where(user_id: current_user.id).first
      if current_user.id == @product.user_id || @product.purchaser_id.present?
        redirect_to root_path
      elsif @address.blank?
        redirect_to new_address_path(@user)
        # 売り切れの時に直打ち遷移しないようにする
      end
    else
      redirect_to root_path
    end
  end

  def pay
    # 既に購入されていないか？ されていたらroot_path
    if user_signed_in?
      @address = Address.where(user_id: current_user.id).first
      @card = Card.where(user_id: current_user.id).first
      if @product.purchaser_id.present? || @product.user_id == current_user.id
        redirect_to root_path
      elsif @card.blank?
        # カード情報がなければ、カード登録画面に遷移
        redirect_to new_card_path
      else
        Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
        customer = Payjp::Customer.retrieve(@card.payjp_id)
        Payjp::Charge.create(
          amount: @product.price,
          customer: customer.id,
          currency: 'jpy'
        )
        # 売り切れになるので、productの情報をアップデートして売り切れにする
        if @product.update(purchaser_id: current_user.id)
          redirect_to action: 'show', id: @product.id
        else
          redirect_to action: 'show', id: @product.id
        end
      end
    else
      redirect_to root_path
    end
  end

  def get_category_children
    # 選択された親カテゴリーに紐付く子カテゴリーの配列を取得
    @category_children = Category.find_by(id: "#{params[:parent_id]}", ancestry: nil).children
  end

  def get_category_grandchildren
    # 選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end

  def search
    @products = Product.search(params[:keyword])

  end

  private
  def product_params
    params.require(:product).permit(
      :name,
      :introduction,
      :price,
      :category_id,
      :brand_id,
      :shipping_region_id,
      :shipping_payer_id,
      :preparation_term_id,
      :product_condition_id,
      images_attributes: [:image, :_destroy, :id]
    ).merge(user_id: current_user.id)
  end

  def set_category
    @category_parent_array = Category.where(ancestry: nil).limit(13)
  end

  def set_parent
    @parents = Category.all.order(id: "ASC").limit(10)
  end

  def set_product
    @product = Product.find(params[:id])
  end
  
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.haml
.content-bg-gray
  - if @product.errors.any?
    .product-form__errors
      %div.product-form__errors__count= "#{@product.errors.full_messages.count}件のエラーが発生しました"
      %ul
        - @product.errors.full_messages.each do |message|
          %li.error-message= message
  .shadowed-rounded-rectangle
    = form_with(model: @product, local: true, class: "product-new-form") do |f|
      %section.mainbox-header
        %h2.mainbox-header__text
          商品の情報を入力
        .product__block__form
        .new-wrapper
          %span.label_title.profile-form__label
            出品画像
            %span.require 必須
            %p.upload_limit 最大10枚までアップロードできます
            %ul#previews
              - @product.images.each_with_index do |img, i|
                %li.image-preview
                  %label.upload-label{style:"display: none;"}
                    .input-area
                      = f.fields_for :images do |image|
                        = image.file_field :image, value: img.image, class: "hidden image_upload"
                        = image.hidden_field :id, value: img.id, name:"product[image][#{i}]"
                  .image-preview__wrapper
                    = image_tag img.image.to_s, size: "80x80", class:"preview"
                  .image-preview_btn
                    .image-preview_btn_delete
                      削除
          .product__block__form__name
            = f.label "商品名", class: "profile-form__label"
            %h4.require
              必須
              %br/
            = f.text_field :name, placeholder:"40文字まで", class: "input-form-xregular"
          .product__block__form__introduction
            = f.label "商品の説明", class: "profile-form__label"
            %h4.require
              必須
              %br/
            = f.text_area :introduction, placeholder:"商品の説明", class: "input-form-xlarge"
        .content__product-detail
          .content_product-detail__category
            .listing-product-detail__category
              %h3.grey 商品の詳細
              = f.label "カテゴリー", class: "profile-form__label"
              %h4.require
                必須
                %br/
            .listing-select-wrapper--edit
              .listing-select-wrapper--edit__parent
                = f.collection_select :root_category_id, @parent_categories, :id, :name, {selected: @product.category.root_id}, {class: 'listing-select-wrapper__box--select', id: 'parent_category_edit'}
              .listing-select-wrapper--edit__child
                = f.collection_select :category_id, @product.category.parent.parent.children, :id, :name ,{prompt: "選択してください", selected: @product.category.parent_id}, {class: 'listing-select-wrapper--edit__child--select', class: "input-form-xregular", id: 'child_category_edit', name: "" }
              .listing-select-wrapper--edit__grandchild
                = f.collection_select :category_id,@product.category.parent.children, :id, :name ,{prompt: "選択してください", selected: @product.category.id}, {class: 'listing-select-wrapper--edit__grandchild--select', class: "input-form-xregular", id: 'grandchild_category_edit', name: "product[category_id]" }
          .content_product-detail__condition
            = f.label "商品の状態", class: "profile-form__label"
            %h4.require
              必須
              %br/
            = f.collection_select :product_condition_id, ProductCondition.all, :id, :condition, {prompt: "選択して下さい"}, {class: "input-form-xregular"}
          .content__product-shipping
            .content__product-shipping__region
              %h3.grey 配送について
              = f.label "発送元の地域", class: "profile-form__label"
              %h4.require
                必須
                %br/
              = f.collection_select :shipping_region_id, ShippingRegion.all, :id, :region, {prompt: "選択して下さい"}, {class: "input-form-xregular"}
            .content__product-shipping__date
              = f.label "発送までの日数", class: "profile-form__label"
              %h4.require
                必須
                %br/
              = f.collection_select :preparation_term_id, PreparationTerm.all, :id, :term, {prompt: "選択して下さい"}, {class: "input-form-xregular"}
          .content__product-price
            .content__product-price__limitation
              %h3.grey 価格(¥300~9,999,999)
            .content__product-price__sold
              = f.label "販売価格", class: "profile-form__label"
              %h4.require
                必須
                %br/
              = f.number_field :price, style: "text-align:right", class: "input-form-middle"
              .content__product-price__sold__yen
                %h3 ¥
          .xsubmit
            =f.submit "更新する", class: "xsubmit__btn"
= render partial: 'layouts/footer'

app/views/products/index.html.haml
.wrapper
  / <div class="header">ヘッダー(部分テンプレート)</div>
  .content
    .content__products
      .item-top
        .item-top__title
          お気に入りした商品
        .item-top__link
          = link_to "もっと見る>", "/users/likes", class: "item-top__link--btn"
      .item-box
        -if user_signed_in?
          - current_user.like_products.limit(10).each do |product|
            .item-box__product
              = link_to product_path(product), class: "item-box__product--btn" do
                .image
                  - product.images.limit(1).each do |images|
                    = image_tag images.image.to_s, size: "200x200", class: "image__tag"
                .like_prodct__index
                  .vertical_like
                    - unless product.like_user(current_user.id).blank?
                      %i.fa.fa-star{:class => "fa-spin", :style => "color: red;"}
                      %span いいね!
                      = product.likes.count
                    - else
                      %i.fa.fa-star{:class => "fa-spin", :style => "color: grey;"}
                      %span いいね!
                      = product.likes.count
                .price
                  .price__box
                    ¥ #{product.price.to_s(:delimited, delimiter: ',')}
                -if product.purchaser_id.present?
                  .items-box_photo__sold-index
                    .items-box_photo__sold-index__inner
                      SOLD
        - else
    .content__products
      -@category_parents.each do |parent|
        .categories-index__wrapper
          .item-top
            .products-index__category-title
              = parent.name
            .item-top__link
              = link_to "もっと見る>", category_path(parent.id), class: "item-top__link--btn"
          .item-box
            -@category_products.limit(10).each do |product|
              -if parent.id == product.category.root_id
                .item-box__product
                  = link_to product_path(product), class: "item-box__product--btn" do
                    -product.images.limit(1).each do |images|
                      .image
                        = image_tag images.image.to_s, size: "200x200", class: "image__tag"
                      -if user_signed_in?
                        .like_prodct__index
                          .vertical_like
                            - unless product.like_user(current_user.id).blank?
                              %i.fa.fa-star{:class => "fa-spin", :style => "color: red;"}
                              %span いいね!
                              = product.likes.count
                            - else
                              %i.fa.fa-star{:class => "fa-spin", :style => "color: grey;"}
                              %span いいね!
                              = product.likes.count
                      - else
                        .like_prodct__index
                          .vertical_like
                            %i.fa.fa-star{:class => "fa-spin", :style => "color: grey;"}
                            %span いいね!
                            = product.likes.count
                      .price
                        .price__box
                          ¥ #{product.price.to_s(:delimited, delimiter: ',')}
                      -if product.purchaser_id.present?
                        .items-box_photo__sold-index
                          .items-box_photo__sold-index__inner
                            SOLD
= render partial: 'layouts/footer'
= render partial: 'layouts/post-btn'

app/views/products/new.html.haml
.content-bg-gray
  - if @product.errors.any?
    .product-form__errors
      %div.product-form__errors__count= "#{@product.errors.full_messages.count}件のエラーが発生しました"
      %ul
        - @product.errors.full_messages.each do |message|
          %li.error-message= message
  .shadowed-rounded-rectangle
    = form_with(model: @product, local: true, class: "product-new-form") do |f|
      %section.mainbox-product-header
        %h2.mainbox-header__text
          商品の情報を入力
        .product__block__form
        .new-wrapper
          %span.label_title.profile-form__label
            出品画像
            %span.require 必須
            %p.upload_limit 最大10枚までアップロードできます
          .product-new__field__uploader
            = f.fields_for :images do |image|
              // 写真のプレビューとインプットボタンのul
              %ul#previews
                %li.input
                  // 画像を取り込むインプットボタン
                  %label.upload-label
                    .upload-label__text
                      %div
                        %p クリックしてファイルをアップロード
                    .input-area.display-none
                      = image.file_field :image, class: "hidden image_upload"
          .product__block__form__name
            = f.label "商品名", class: "profile-form__label"
            %h4.require
              必須
            %br/
            = f.text_field :name, placeholder:"40文字まで", class: "form__group__name", class: "input-form-xregular"
        .product__block__form__introduction
          = f.label "商品の説明", class: "profile-form__label"
          %h4.require
            必須
          %br/
          = f.text_area :introduction, placeholder:"商品の説明", class: "input-form-xlarge"
      .content__product-detail
        .content_product-detail__category
        .listing-form-box
          .listing-product-detail__category
            %h3.grey 商品の詳細
            = f.label "カテゴリー", class: "profile-form__label"
            %h4.require
              必須
            %br/
            .listing-select-wrapper
              .listing-select-wrapper__box
                = f.collection_select :root_category_id, @category_parent_array, :id, :name, {prompt: "---"}, {class: 'listing-select-wrapper__box--select', id: 'parent_category'}
        .content_product-detail__condition
          = f.label "商品の状態", class: "profile-form__label"
          %h4.require
            必須
          %br/
          = f.collection_select :product_condition_id, ProductCondition.all, :id, :condition, {prompt: "選択して下さい"}, {class: "select input-form-xregular"}
      .content__product-shipping
        .content__product-shipping__region
          %h3.grey 配送について
          = f.label "発送元の地域", class: "profile-form__label"
          %h4.require
            必須
          %br/
          = f.collection_select :shipping_region_id, ShippingRegion.all, :id, :region, {prompt: "選択して下さい"}, {class: "select input-form-xregular"}
        .content__product-shipping__date
          = f.label "発送までの日数", class: "profile-form__label"
          %h4.require
            必須
          %br/
          = f.collection_select :preparation_term_id, PreparationTerm.all, :id, :term, {prompt: "選択して下さい"}, {class: "select input-form-xregular"}
      .content__product-price
        .content__product-price__limitation
          %h3.grey 価格(¥300~9,999,999)
        .content__product-price__sold
          = f.label "販売価格", class: "profile-form__label"
          %h4.require
            必須
          %br/
          = f.number_field :price, style: "text-align:right", class: "input-form-middle"
          .content__product-price__sold__yen
            %h3 ¥
      .xsubmit
        =f.submit "出品する",class: "xsubmit__btn"
=render partial: 'layouts/footer'

app/views/products/purchase.html.haml
.purchase-confirmation
  .purchase-confirmation__content
    .purchase-confirmation__content__title
      購入内容の確認
    .purchase-confirmation__content__item-detail
      .purchase-confirmation__content__item-detail__info.item-detail__info
        .item-detail__info__image
          = image_tag @image.image.to_s, size: '100x100', class: 'item-detail__info__image--tag'
        .item-detail__info__right
          .item-detail__info__right--name
            = @product.name
          .item-detail__info__right--price
            %strong ¥ #{@product.price.to_s(:delimited, delimiter: ',')} 円
            (税込み)
            %br
            出品者負担
    -# .purchase-confirmation__content__card-info
    -#   .purchase-confirmation__content__card-info--detail
    -#     カード情報
    .purchase-confirmation__content__address
      .purchase-confirmation__content__address__shipping-address.shipping-address
        .shipping-address__title
          %strong 配送先
          = link_to "変更する>", "#", class: 'shipping-address__title--btn'
        .shipping-address__detail
          .shipping-address__detail--zipcode
            = @address.zip_code.to_s.gsub(/(\d{3})(\d{4})/, '\1-\2')
          .shipping-address__detail--region
            #{@address.prefecture} #{@address.city} #{@address.street_number} #{@address.apartment}
          .shipping-address__detail--user-name
            #{@address.last_name} #{@address.first_name}
    .purchase-confirmation__content__purchase-item
      = link_to "クレジットカードで支払う", pay_product_path(params[:id]), class: 'purchase-confirmation__content__purchase-item--btn'
    .purchase-confirmation__content__back
      =link_to "前に戻る", product_path(@product), class: 'purchase-confirmation__content__back--btn'


  -# = "**** **** **** " + @default_card_information.last4
  -# %br
  -# - exp_month = @default_card_information.exp_month.to_s
  -# - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
  -# = exp_month + " / " + exp_year

app/views/products/search.html.haml
-# .items
-#   .item-title
-#   .boxs
-#     - @products.each do |products|
-#       - products.images.each do |images|
-#         .box
-#           = link_to product_path(products) do
-#             .image
-#               = image_tag images.image.to_s, size: "100x100"
-#             .price
-#               = products.price
-#             .text
-#               = products.name
-#             -if products.purchaser_id.present?
-#               .items-box_photo__sold
-#                 .items-box_photo__sold__inner
-#                   SOLD

.wrapper
  .products-search
    .products-search__boxs
      - @products.each do |products|
        - products.images.each do |images|
          .products-search__boxs__item
            = link_to product_path(products) do
              .products-search__boxs__item--image
                = image_tag images.image.to_s, size: "200x200", class: "products-search__boxs__item--image--modify"
              .products-search__boxs__item--price
                ¥ #{products.price.to_s(:delimited, delimiter: ',')}
              .products-search__boxs__item--name
                = products.name
              -if products.purchaser_id.present?
                .items-box_photo__sold-products-search
                  .items-box_photo__sold-products-search__inner
                    SOLD

app/views/products/show.html.haml
.wrapper-product-show
  .main
    .product-show
      .product-show__item-name
        = @product.name
      .product-show__box
        .product-show__box__images-show
          .product-show__box__images-show__main
            = image_tag @image.image.to_s, size: "250x300", class: "main-image"
            -if @product.purchaser_id.present?
              .items-box_photo__sold-products-show
                .items-box_photo__sold-products-show__inner
                  SOLD
          .product-show__box__images-show__subs
            - @images.each.with_index(1) do |image, index|
              .product-show__box__images-show__subs--sub
                = image_tag image.image.to_s, size: "40x50", class: "sub-image"
        %table.product-show__box__table-info
          %tbody
            %tr
              %th.th-side__top
                出品者
              %td.td-side__top
                = link_to user_path(@product.user.id) do
                  = @product.user.nickname
                %br
                  %ul.evaluation
                    %li.evaluation
                      = icon('fas', 'grin',  class: "good")
                      %i
                        = @evaluation_good_sum.count
                    %li.evaluation
                      = icon('fas', 'meh',  class: "normal")
                      %i
                      = @evaluation_normal_sum.count
                    %li.evaluation
                      = icon('fas', 'frown',  class: "bad")
                      %i
                        = @evaluation_bad_sum.count
                -# %ul.evaluation
                -#   %li
                -#     = button_to "/products/#{@product.id}", {method: :post, class: "eva", params: {evaluation: 1}} do
                -#       = @evaluation_good_sum
                -#   %li
                -#     = button_to "/products/#{@product.id}", {method: :post, class: "eva", params: {evaluation: 2}} do
                -#       = @evaluation_normal_sum
                -#   %li
                -#     = button_to "/products/#{@product.id}", {method: :post, class: "eva", params: {evaluation: 3}} do
                -#       = @evaluation_bad_sum
            %tr
              %th
                カテゴリー
              %td
                = @children.root.name
                %br
                = @children.parent.name
                %br
                = @children.name
            %tr
              %th
                ブランド名
              %td
                ブランド
            %tr
              %th
                商品の状態
              %td
                = @product.product_condition.condition
            %tr
              %th
                配送料の負担
              %td
                出品者 
            %tr
              %th
                配送元の地域
              %td
                = @product.shipping_region.region
            %tr
              %th.th-side__bottom
                発送の目安
              %td.td-side__bottom
                = @product.preparation_term.term
      .product-show__price
        .product-show__price__tax-included
          ¥ #{@product.price.to_s(:delimited, delimiter: ',')}
          %span.price-tax (税込)
          %span.product-show__price__tax-included--postage
            送料込み
      .product-show__purchase-item
        -# -unless user_signed_in? && @product.user_id == current_user.id
        -if user_signed_in? && @product.user_id != current_user.id && @product.purchaser_id.blank?
          = link_to "購入画面に進む", purchase_product_path(params[:id]), class: "product-show__purchase-item--btn"
        -elsif user_signed_in? && @product.user_id == current_user.id && @product.purchaser_id.blank?
          -# - if user_signed_in? && current_user.id == @product.user_id
          .product-poster-btn
            = link_to '編集', "/products/#{@product.id}/edit", method: :get, class: "product-edit-btn"
            = link_to '削除', "/products/#{@product.id}", method: :delete, class: "product-delete-btn"
        -elsif @product.purchaser_id.blank?
          = link_to "新規会員登録へ進む", new_user_registration_path, class: "product-show__purchase-item--btn"
        -elsif user_signed_in? && @product.purchaser_id == current_user.id && @evaluation.blank?
          = link_to "出品者を評価する", new_product_evaluation_path(@product), class: "product-show__purchase-item--btn"
        -elsif @product.purchaser_id.present?
          = link_to "売り切れです", root_path, class: "product-show__purchase-item--btn"
        -else
          = link_to "トップへ戻る", root_path, class: "product-show__purchase-item--btn"
      .like-btn{:id => "likes_buttons_#{@product.id}"}
        = render partial: 'likes/like', locals: { product: @product, likes: @likes}
      %h4.product-show__introduction
        = @product.introduction
      .comment-container
        - if current_user
          = form_with model: [@product, @comment], local: true, id: "new_comment", class: "comment-form" do |form|
            = form.text_area :text, placeholder: "コメントする", rows: "2", class: "textbox comment-form__field"
            = form.submit "コメントする", class: "form__submit comment-form__submit"
        - else
          %strong.no-login-user
            ※※※ コメントの投稿には新規登録/ログインが必要です ※※※
        %h4.comment-lists < コメント一覧 >
        - if @comments
          .comments-display
            - @comments.each do |comment|
              %strong
                %p.comments-display__detail
                  = link_to "#{comment.user.nickname} さん：", "/users/#{comment.user_id}"
                  = comment.text
=render partial: 'layouts/footer'