config/routes.rb
Rails.application.routes.draw do
  get 'likes/create'
  get 'likes/destroy'
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  root 'products#index'

  resources :profiles, only: [:edit, :update]
  resources :addresses, only: [:edit, :update, :new, :create]

  resources :users, only: [:edit, :update] do
    collection do
      get 'likes'
    end

    member do
      get 'history'
    end
  end
  
  devise_scope :user do
    get "log_in", to: "users/sessions#new"
    get 'log_out', to: "users#log_out"
    delete 'log_out', to: 'users/sessions#destroy'

  end

  resources :products do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'search'
    end
    resources :evaluations, only: [:new, :create]
    resources :likes, only: [:create, :destroy]
    resources :comments, only: :create
    post "", to: "evaluations#create"
    
    member do
      get 'purchase'
      get 'pay'
    end

  end

  resources :likes, only: [:index, :show, :create, :destroy]

  resources :categories, only: [:index, :show]

  resources :cards, only: [:new, :create, :show, :destroy]

  resources :users, only: [:index, :show] do
    collection do
      get :likes
    end
  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user

  validates :first_name,
            :last_name,
            :first_name_kana,
            :last_name_kana,
            :zip_code,
            :prefecture,
            :city,
            :street_number,
            presence: { message: "を入力してください"}

  validates :zip_code, format: {with: /\A[0-9]{7}\z/}

  enum prefecture: {
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47
  }
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  has_ancestry
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/evaluation.rb
class Evaluation < ApplicationRecord
  belongs_to :user
  belongs_to :product

  # 同じ商品に対して一意性
  validates :product_id, uniqueness: true
end

app/models/image.rb
class Image < ApplicationRecord
  # config.autoload_paths += Dir[Rails.root.join('app', 'uploaders')]
  mount_uploader :image, ImageUploader
  belongs_to :product
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :product, counter_cache: :likes_count
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  belongs_to :category
  belongs_to :brand, optional: true
  belongs_to :product_condition
  belongs_to :preparation_term
  belongs_to :shipping_region
  belongs_to :shipping_payer, optional: true
  has_many :comments, dependent: :destroy
  has_many :evaluations, dependent: :destroy

  validates :images, presence: { message: "を入力してください"}
  validates :name,  presence: { message: "を入力してください"}, length: { maximum: 40 }
  validates :introduction,  presence: { message: "を入力してください"}
  validates :price, presence: { message: "を入力してください"}
  validates :price, :numericality => { greater_than: 300, less_than: 9999999 } 
  
  has_many :likes, dependent: :destroy
  

  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end

  def self.search(keyword)
    return Product.all unless keyword
    Product.where('name LIKE?', "%#{keyword}%")
  end

end

app/models/profile.rb
class Profile < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user

  #validates_associated :user
  validates :first_name, :last_name, format: { with: /\A[ぁ-んァ-ン一-龥]/,
    message: "全角で入力してください" }
  validates :first_name_kana, :last_name_kana, format: { with: /\A[ァ-ヶー－]+\z/,
    message: "全角カナで入力してください" }
  validates :birth_date, presence: true
end

app/models/shipping_payer.rb
class ShippingPayer < ApplicationRecord
  has_many :products
end

app/models/shipping_region.rb
class ShippingRegion < ApplicationRecord
  has_many :products

  enum region: {
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true

  has_one :profile
  accepts_nested_attributes_for :profile
  has_one :address
  has_one :card
  has_many :products
  has_many :comments
  has_many :evaluations

  has_many :likes, dependent: :destroy
  has_many :like_products, through: :likes, source: :product
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.haml
.footer
  .footer__logo
    %h3.white.footer__logo__text
      © FURIMA

app/views/layouts/_post-btn.html.haml
.post-btn
  .post-btn__wrapper
    .post-btn__text
      出品
    .post-btn__icon
    = link_to new_product_path do
      = icon('fas', 'plus')

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FleamarketSample76c
    %script{:src => "https://js.pay.jp/", :type => "text/javascript"}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    %body
      %nav.header
        .header__top
          .header__top__title
            = link_to products_path do
              = image_tag "http://furima.tokyo/assets/logo-d3d78326971d78b06e3d6f0ba666d025a8ad681286b4d9e00e7dbe8673bcfd23.svg", size: "126x36"
          .category-search
            %ul.snav
              %li.snav__category-lists__headline
                = link_to "カテゴリー", categories_path, class: "navigation-btn"
                %ul.snav__category-lists__parents
                  - @parents.roots.each do |parent|
                    %li.snav__category-lists__parent
                      = link_to category_path(parent.id), class: "snav__category-list__text" do
                        = parent.name
                      %ul.snav__category-lists__children
                        - parent.children.each do |child|
                          %li.snav__category-lists__child
                            = link_to category_path(child.id), class: "snav__category-list__text" do
                              = child.name
                            %ul.snav__category-lists__grandchildren
                              - child.children.each do |grandchild|
                                %li.snav__category-lists__grandchild
                                  = link_to category_path(grandchild.id), class: "snav__category-list__text" do
                                    = grandchild.name
          .header__top__search
            = form_with url: search_products_path, local: true, method: :get, class: "form" do |form|
              = form.text_field :keyword, placeholder: "何かお探しですか？", class: "form-text"
              %button.search
          - if user_signed_in?
            .new-register
              = link_to "マイページ", users_path, class: "new-register"
            .login
              = link_to "ログアウト", destroy_user_session_path, method: :delete, chass: "login"
          - else
            .new-register
              = link_to "新規登録", new_user_registration_path, class: "new-register"
            .login
              = link_to "ログイン", log_in_path, class: "login"
    = yield